# .streamlit/secrets.toml

# GoldAPI (use the exact token string you send in the x-access-token header)
GOLDAPI_KEY = "goldapi-grta9sme8izq5i-io"

# ExchangeRatesAPI (paid). If you don't have one, leave these blank and the app will
# automatically fall back to exchangerate.host.
EXCHANGE_API_BASE = "https://api.exchangeratesapi.io/v1"
EXCHANGE_API_KEY  = "0768a3c333494f853f45a543e7d481a9"
